# Test instantiations of both resource macros, with permissive policies. Policies
# are added after `use` because Elixir's `use` takes no `do` block -- which is
# also the ordering that lets the generated bypass sit in front of them, and is
# what a host adding its own rules should do.

defmodule AshDecisions.Test.Definition do
  @moduledoc false
  use AshDecisions.Resources.Definition,
    domain: AshDecisions.Test.Domain,
    repo: AshDecisions.TestRepo

  policies do
    bypass do
      authorize_if(always())
    end
  end
end

defmodule AshDecisions.Test.Evaluation do
  @moduledoc false
  use AshDecisions.Resources.Evaluation,
    domain: AshDecisions.Test.Domain,
    repo: AshDecisions.TestRepo,
    definition: AshDecisions.Test.Definition

  policies do
    bypass do
      authorize_if(always())
    end
  end
end

defmodule AshDecisions.Test.Domain do
  @moduledoc false
  use Ash.Domain

  resources do
    resource(AshDecisions.Test.Definition)
    resource(AshDecisions.Test.Evaluation)
  end
end

# A domain with only one of the two kinds in it, so `for_domain/1` has something
# incomplete to report on. A host that registers the definition resource and
# forgets the evaluation resource should be told which one is missing, not handed
# a match error from somewhere further in.
defmodule AshDecisions.PartialTest.Definition do
  @moduledoc false
  use AshDecisions.Resources.Definition,
    domain: AshDecisions.PartialTest.Domain,
    repo: AshDecisions.TestRepo
end

defmodule AshDecisions.PartialTest.Domain do
  @moduledoc false
  use Ash.Domain

  resources do
    resource(AshDecisions.PartialTest.Definition)
  end
end
