defmodule AshDecisions.BaseResourceTest do
  @moduledoc """
  `:base` — decision resources sitting on a host application's base resource.

  Without this option the resource macros emit `use Ash.Resource` themselves, so
  a definition and an evaluation cannot inherit anything the application arranged
  for every other record it owns: ownership, provenance, soft delete, the audit
  hook, the policy set. "A decision record is an ordinary owned, audited,
  tenant-scoped row" would be a design intention rather than something the code
  permitted.
  """

  use AshDecisions.DataCase, async: false

  require Ash.Query

  alias AshDecisions.BaseTest.{Definition, Evaluation, NoPolicies}
  alias AshDecisions.Scope

  @discount File.read!("test/fixtures/discount.dmn")

  defp key, do: "k#{System.unique_integer([:positive])}"

  defp evaluation_attrs do
    %{
      definition_id: Ecto.UUID.generate(),
      definition_key: key(),
      definition_version: 1,
      decision_id: "decision_discount"
    }
  end

  describe "a resource built on a base" do
    test "goes through the base module rather than Ash.Resource" do
      assert Definition.base_resource?()
      assert Definition.ash_decisions_kind() == :definition
    end

    test "still has the data layer, table and actions the macro provides" do
      assert Ash.Resource.Info.data_layer(Definition) == AshPostgres.DataLayer
      assert AshPostgres.DataLayer.Info.table(Definition) == "dmn_definitions"

      action_names = Enum.map(Ash.Resource.Info.actions(Definition), & &1.name)
      assert :publish in action_names
      assert :retire in action_names
      assert :save_xml in action_names
    end

    test "carries both policy sets: the base's, and the generated bypass" do
      policies = Ash.Policy.Info.policies(Definition)

      assert Enum.any?(policies, & &1.bypass?),
             "the bypass should survive being emitted after the base's policies"

      refute Enum.all?(policies, & &1.bypass?), "the base's own policy should still be there"
    end
  end

  describe "authorization when the bypass comes first" do
    # `AshDecisions.BaseTest.PolicylessBase` leaves authorization to the resource,
    # so the macro's bypass is the first policy and the host's rule follows it.

    test "the library writes without an actor" do
      evaluation = Evaluation.create!(evaluation_attrs(), Scope.engine(%Scope{}))
      assert evaluation.decision_id == "decision_discount"
    end

    test "the host's own rule still holds everyone else out" do
      attrs = evaluation_attrs()

      assert_raise Ash.Error.Forbidden, fn -> Evaluation.create!(attrs) end
      assert %{} = Evaluation.create!(attrs, actor: %{id: Ecto.UUID.generate()})
    end
  end

  describe "authorization when the base's policies come first" do
    # `AshDecisions.BaseTest.Resource` ships its own policy set, and `use` expands
    # it before anything the ash_decisions macro emits. A bypass only
    # short-circuits the policies declared after it, so the library does *not*
    # get through here.
    #
    # This is pinned rather than fixed on purpose: it is Ash's semantics, not
    # ours, and a host needs to know which arrangement it has. The two ways out
    # are in `AshDecisions.Config.engine_actor/0`.

    test "the library is forbidden, because the base's policy is ahead of the bypass" do
      assert_raise Ash.Error.Forbidden, fn ->
        Definition.create!(
          %{key: key(), name: "Discount", xml: @discount},
          Scope.engine(%Scope{})
        )
      end
    end

    test "engine_actor: configuring an actor the base admits is the way out" do
      Application.put_env(:ash_decisions, :engine_actor, %{id: Ecto.UUID.generate()})
      on_exit(fn -> Application.delete_env(:ash_decisions, :engine_actor) end)

      definition =
        Definition.create!(
          %{key: key(), name: "Discount", xml: @discount},
          Scope.engine(%Scope{})
        )

      assert definition.version == 1
    end

    test "a caller the base's own policy admits gets through without the bypass" do
      definition =
        Definition.create!(
          %{key: key(), name: "Discount", xml: @discount},
          actor: %{id: Ecto.UUID.generate()}
        )

      assert definition.status == :draft
    end
  end

  describe "conflicting options" do
    test ":base with tenant?: true refuses to compile" do
      # Two multitenancy strategies on one resource is not a thing a host wants
      # to discover at runtime, and a base worth inheriting already owns tenancy.
      assert_raise ArgumentError, ~r/`:base` and `tenant\?: true` cannot be combined/, fn ->
        Code.compile_string("""
        defmodule AshDecisions.BaseResourceTest.Conflicting do
          use AshDecisions.Resources.Definition,
            domain: AshDecisions.BaseTest.Domain,
            repo: AshDecisions.TestRepo,
            base: AshDecisions.BaseTest.Resource,
            tenant?: true
        end
        """)
      end
    end
  end

  describe "policies?: false" do
    test "removes the bypass, leaving the host to grant it" do
      assert Ash.Policy.Info.policies(NoPolicies) == []
    end

    test "an authorizer with nothing to satisfy refuses even this package" do
      assert_raise Ash.Error.Forbidden, fn ->
        NoPolicies
        |> Ash.Query.for_read(:read)
        |> Ash.read!(Scope.engine(%Scope{}))
      end
    end
  end
end
