defmodule AshDecisions.TenancyTest do
  @moduledoc """
  `tenant?: true`, exercised against tenant-scoped tables.

  An option that generates a multitenancy strategy is worth nothing on its own.
  What makes it real is that a suite runs against tables that actually have the
  column, so that "the tenant was discarded somewhere between the caller and the
  row" is a failing test rather than something a customer discovers.

  These resources carry no policies of their own, so every assertion here is also
  an assertion that this package's calls are recognised by the generated bypass.
  """

  use AshDecisions.DataCase, async: false

  require Ash.Query

  alias AshDecisions.Scope
  alias AshDecisions.TenantTest.{Definition, Evaluation}

  @discount File.read!("test/fixtures/discount.dmn")

  setup do
    %{
      a: Ecto.UUID.generate(),
      b: Ecto.UUID.generate(),
      key: "k#{System.unique_integer([:positive])}"
    }
  end

  defp create(tenant, key, name \\ "Discount") do
    Definition.create!(
      %{key: key, name: name, xml: @discount},
      Scope.engine(%Scope{tenant: tenant})
    )
  end

  test "the tenant lands on the row", %{a: a, key: key} do
    definition = create(a, key)
    assert definition.organization_id == a
  end

  test "two tenants hold the same key independently, each at version 1", %{a: a, b: b, key: key} do
    assert create(a, key).version == 1
    assert create(b, key).version == 1
  end

  test "versions are counted within a tenant, not across all of them", %{a: a, b: b, key: key} do
    first = create(a, key)
    Definition.publish!(first, Scope.engine(%Scope{tenant: a}))

    # B has never published anything under this key, so B's next version is 1
    # even though A is on 2. A version counter that consulted every tenant's rows
    # would give B version 3 here, and B's audit trail would have gaps in it that
    # correspond to another customer's edits.
    assert create(a, key, "second").version == 2
    assert create(b, key).version == 1
  end

  test "one tenant cannot see another's definitions", %{a: a, b: b, key: key} do
    create(a, key)

    assert [_] = read_all(Definition, a)
    assert read_all(Definition, b) == []
  end

  test "evaluations are scoped the same way", %{a: a, b: b, key: key} do
    definition = create(a, key)

    Evaluation.create!(
      %{
        definition_id: definition.id,
        definition_key: definition.key,
        definition_version: definition.version,
        decision_id: "decision_discount",
        inputs: %{"orderTotal" => 1200},
        outputs: %{"discount" => 0.15},
        matched_rule_ids: ["rule_gold_large"],
        hit_policy: "UNIQUE"
      },
      Scope.engine(%Scope{tenant: a})
    )

    assert [evaluation] = read_all(Evaluation, a)
    assert evaluation.organization_id == a
    assert read_all(Evaluation, b) == []
  end

  test "the draft uniqueness rule is per tenant", %{a: a, b: b, key: key} do
    create(a, key)

    # B holding a draft of the same key is not a conflict, and a uniqueness check
    # that read across tenants would report one.
    assert create(b, key).version == 1

    assert {:error, %Ash.Error.Invalid{}} =
             Definition.create(
               %{key: key, name: "again", xml: @discount},
               Scope.engine(%Scope{tenant: a})
             )
  end

  test "latest_published is scoped too", %{a: a, b: b, key: key} do
    a_definition = create(a, key)
    Definition.publish!(a_definition, Scope.engine(%Scope{tenant: a}))
    create(b, key)

    assert [published] = Definition.latest_published!(key, Scope.engine(%Scope{tenant: a}))
    assert published.organization_id == a
    assert Definition.latest_published!(key, Scope.engine(%Scope{tenant: b})) == []
  end

  defp read_all(resource, tenant) do
    resource
    |> Ash.Query.for_read(:read)
    |> Ash.read!(Scope.engine(%Scope{tenant: tenant}))
  end
end
